language: c
compiler: gcc
script: make
dist: trusty
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libtiff-dev
 - sudo apt-get install libconfig-dev
 - sudo apt-get install libbsd-dev
